#pragma once
#define USE_CPU 1
#define EVOLVE_ON_GPU 0
#define VISION_4 1
#define VISION_8 0
#define WIDTH 12
#define HEIGHT 12
#define CELL_SIZE 20
#define INPUT_SIZE 12
#define HIDDEN_NEURONS_SIZE 6
#define HIDDEN_NEURONS_1_SIZE 6
#define OUTPUT_NEURONS_SIZE 3
#define LOOK_DIRECTIONS 4
#define POP_SIZE 5000
#define MUTATION_RATE 15
#define MUTATION_SIZE 1
#define CHILDESS_PARENT_PROB -1
#define GENERATION 3000
#define BEST_SNAKES_SIZE 20

enum {
	UP = 0, RIGHT = 1, DOWN = 2, LEFT = 3,
	SNAKE = 5, APPLE = 10, EMPTY = 1, HEAD = 8
};

#define INPUT_WEIGHTS_SIZE (INPUT_SIZE * HIDDEN_NEURONS_SIZE)
#define HIDDEN_WEGHTS_SIZE (HIDDEN_NEURONS_SIZE * HIDDEN_NEURONS_1_SIZE)
#define OUTPUT_WEIGHTS_SIZE (HIDDEN_NEURONS_1_SIZE * OUTPUT_NEURONS_SIZE)
